### ISSUE TITLE
formalise contribution guidelines

### ISSUE THREAD

**Issue by kortschak** [gonum/license#25] opened 2016-10-26 23:42 UTC
I'm pretty sure that we have discussed this in the past, but we have not put forward a document to help newcomers. This repo (while we are still across multiple repos) seems like the place to put things.

There should be documents for approach to contribution in PRs/design and also for issue reporting. In my view, golang.org does both of those pretty well. I would also like to see something that guides us as more experienced contributors in how we deal with new contributors (I'm hoping we don't do a terrrible job here). @Armadilloa16 sent me a [link](http://sarah.thesharps.us/2014/09/01/the-gentle-art-of-patch-review/) the other day that could form the basis for that.

**Comment by jonlawlor** [comment] 2016-10-27 14:34
I think this is a good idea.  I would suggest putting it into a CONTRIBUTING.md file (either in each repo, or one with a link to the master one in this repo) because that way whenever anyone creates an issue or opens a pull, they see a small header over it with a link to the contribution guidelines, as per https://help.github.com/articles/setting-guidelines-for-repository-contributors/.

![image](https://cloud.githubusercontent.com/assets/4468162/19771421/e63be566-9c30-11e6-9733-a3f2e31520d1.png)

**Comment by btracey** [comment] 2016-10-27 14:48
I have been thinking of writing a "Gonum go style" or something like that. We have developed a style for API design, and codifying that seems useful to everyone. I'm not sure if that's what you had in mind.

**Comment by btracey** [comment] 2016-10-27 14:51
I was also thinking about trying to maintain some kind of TODO list across the repos to make it easy for those who want to help. Similarly to Russ's list, I was thinking we could classify at the "design document needed" / "some API discussion needed" / "just go for it", to give some sense of the scale of the request.

**Comment by jonlawlor** [comment] 2016-10-27 15:03
Go's contribution guidelines are good and obviously work well for it.  Another project with nice guidelines is [atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) - although I could do without the emojis.

I think style guides should be included, as it usually is in other contribution guidelines, along with perhaps a basic project layout explaining what goes where, code of conduct, how to start contributing (pull request on license file...) and so on.

Re: TODO list - could you use a [github filter](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Agonum) across the gonum repos, and then add tags in place of that classification?

**Comment by btracey** [comment] 2016-10-27 15:06
We could use a filter for a TODO list, but I'm not sure where we would put "big, non-existant projects", i.e. ODEs, FFT, and machine learning.

**Comment by jonlawlor** [comment] 2016-10-27 15:27
Four options come to mind:

1) Add empty projects to gonum and then add issues to them
2) List the projects on the contribution guidelines, in a section on "what goes where" with a note that they don't exist yet, please send help
3) Add a TODO file to the license project
4) Rename the gonum/license project to "gonum/gonum" or add a project "gonum/design" and then add issues there.  Renaming license to gonum might be a good idea anyway.

**Comment by jonlawlor** [comment] 2016-10-28 03:43
[Here](https://github.com/jonlawlor/scratch/blob/master/CONTRIBUTING.md) is a possible scrawny start.  I tried to combine the go guidelines with the atom ones, and err on the side of brevity.

As an aside, would you like to only allow squash commits in the various gonum repo settings (as per https://github.com/blog/2141-squash-your-commits)?

**Comment by btracey** [comment] 2016-10-28 03:50
I misunderstood the squash feature when I first saw it mentioned. I would be in favor of that. The only thing is I've seen @vladimir-ch use multiple commits in the same PR to good affect, so I'd want to hear his take as well.

**Comment by btracey** [comment] 2016-10-28 04:10
Nice start @jonlawlor .

Here are some thoughts. Some of them may be bad, and I don't have solutions to all of them, but here I go anyway

- We should probably say what's in the scope and what's out of scope for gonum. I don't know that we really know that yet, but something like "broadly useful across disciplines, yes, specific to one, no". There's a pretty broad area between the two, so maybe that's too hard.

- All code should be able to be called with pure go. It's common practice for scientific libraries to just be wrappers around c code, but we aren't that.

- Remove 'in general', and just say "We follow the Go code of conduct."

- Reporting Bugs: I would rather say "If you have code that reproduces the bug, please include it in the issue." We can maybe also include "Consider filing a pull request with a test that triggers the bug". We want an issue filed, even if the user knows how to write a test. Words are often easier to debug then code when trying to verify if the bug is real, and if the code is complicated we don't want it as a PR until the bug is isolated.

- Reporting bugs: We should add something like "please include the subrepo in the title, i.e. stat/distmv: Issue name". I know I have failed to follow that pattern recently, but that's me being wrong.

- We don't really follow 2 LGTM. We generally require one, and may require a second if the code is tricky or could be controverial. We may require more if there was debate.

- I would like to add a note that partial PRs are fine.  I don't know the right words, but the draft proposal / gonum-dev thread should answer part 1 of the three-phase review. Partial PRs can be phase 2. I've done it a few times, saying "this is the kind of interfaces and functions I'm thinking". It doesn't necessarily have to compile (though that's helpful), but it's a lot less work than making nice comments, error messages, etc.

- Hopefully we (me) will write a specific style guide :)

**Comment by kortschak** [comment] 2016-10-28 04:21
I would like the reference to the code of conduct to be weakened. I have issues with formal codification of behaviour over explaining what is desirable. I am happy to refer to the Go code of conduct as an example of the kinds of behaviour that are community expectations, but more than that troubles me.

For the review behaviour, I think that does not belong in the code of conduct section, but rather in a "Contributing" section which would be broken into three parts: "issues", "code contribution" and "code review". Then it become a clear goal-directed explanation, rather than a loose behavioural code. I would also like to see (and would contribute to) fleshing out the text of those sections drawing on the link from Sarah Sharp's blog.

**Comment by jonlawlor** [comment] 2016-10-28 13:30
RE: code of conduct, how about something along the lines of "we expect the same values and behavior as described in the Go code of conduct."

**Comment by jonlawlor** [comment] 2016-10-28 15:02
OK, [here](https://github.com/jonlawlor/scratch/blob/contributing-revision/CONTRIBUTING.md) is an updated version, and [here](https://github.com/jonlawlor/scratch/pull/1/files) is the diff.

**Comment by vladimir-ch** [comment] 2016-10-28 22:04
>> As an aside, would you like to only allow squash commits in the various gonum repo settings?

> I would be in favor of that. The only thing is I've seen @vladimir-ch use multiple commits in the same PR to good affect, so I'd want to hear his take as well.

If the PR is bigger I always try to group the changes into a meaningful sequence of commits. During review I address the comments in similarly scoped commits so that before merging I can do an interactive rebase and reorder and squash the review commits with the PR commits. Finally before merging I rebase onto master and leave the merge commit. If there is an issue, I close it from the merge commit (I've forgotten who mentioned this strategy long time ago here or on gonum-dev). Together with a descriptive name for the branch this leaves a nice group of commits in the git history.

If the PR is small and fits into a single commit, I sometimes leave the merge commit, sometimes not.

The main reason I go through all this is to make the life easier for the reviewer who can comfortably review on per commit basis. Of course, this is a lot of extra work that not every contributor will go through or the PR may not merit it. For those who do it would be a pity to squash the commits.

I would leave it as it is and let the person who is doing the merging decide individually for each PR. Alternatively, the setting could be set to only allow squash commits. Non-squashing merges could be done via command line.

> We should probably say what's in the scope and what's out of scope for gonum.

Perhaps clarifying and listing what we eventually want to have in gonum might help to clarify what's in and out of scope for gonum.

> I would like the reference to the code of conduct to be weakened. I have issues with formal codification of behaviour over explaining what is desirable. I am happy to refer to the Go code of conduct as an example of the kinds of behaviour that are community expectations, but more than that troubles me.

This nicely captures also my position on this.

**Comment by kortschak** [comment] 2016-10-28 23:29
I have commented on @jonlawlor's proposal [there](https://github.com/jonlawlor/scratch/pull/1/files).

**Comment by jonlawlor** [comment] 2016-10-29 20:24
I've incorporated @kortschak's suggestions.  I'm personally in favor of a stronger code of conduct, but if there is a split opinion on it then I don't feel comfortable pushing for it.

[Here](https://github.com/jonlawlor/scratch/blob/contributing-revision/CONTRIBUTING.md) is the updated version again.

**Comment by kortschak** [comment] 2016-10-29 20:46
The issue that I have with a strong code of conduct is that is mimics a legal formalism without having the backing of one. This gets you all the negatives of heavy handedness with none of the benefits of force. One upshot of this is that those involved in enforcing the code start to believe there is a power there - all animals are equal, but some are more equal than others - and overstep.

An illustration of how this can go wrong is [here](https://groups.google.com/d/topic/golang-dev/pOvceAZwLHY/discussion) and [here](https://groups.google.com/d/topic/golang-nuts/MHoI64RyRdY/discussion) (no comments from me on the validity of any of the comments).

Ultimately this is a cultural difference though. There is a fairly stark difference in attitudes towards authority in US, European and Australian culture - with US culture tending more towards acceptance of (and in my view need for) authority.

If it turns out that gonum does need greater force then we can make this stronger, but I would like to tread lightly first.

I have tried to be circumspect in this comment because I have very strong views on authoritarian cultures - hopefully I have not pushed any buttons. If anyone *is* interested in those views I'm happy to discuss elsewhere.

**Comment by jonlawlor** [comment] 2016-10-29 23:43
I think everyone would agree that we can revisit it later if needed.  I included it because I try to do what the go team does.

**Comment by kortschak** [comment] 2016-10-30 00:46
No worries.

**Comment by jonlawlor** [comment] 2016-10-30 01:20
I've incorporated @btracey's suggestions.  Would you like for me to open a pull request here (to move discussion to one place)?

Also there is some small inconsistencies with the package descriptions.  Some have periods at the end, most don't.  Most capitalize Go, some don't.  Would you like for me to resolve them in favor of the majority?  If so I'll open issues at the appropriate repos.

**Comment by kortschak** [comment] 2016-10-30 01:26
That all SGTM.

Go should be capitalised. I don't know if we have decided on capitlisation of gonum (I prefer lc, but that should be decided in discussion). The headings are headings, so they should not have full stops.

**Comment by vladimir-ch** [comment] 2018-12-09 22:00
I think this has been done in the meantime and does not need to be transferred. @kortschak , @btracey ?

**Comment by btracey** [comment] 2018-12-09 22:21
I think so, yes.

**Closed** 2018-12-09 22:56 UTC
